# Generated by Django 6.0 on 2025-12-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tilte',
            new_name='title',
        ),
    ]
